# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  storage: "%env(resolve:FILE_STORAGE)%"
  elasticsearch_enabled: "%env(bool:ELASTICSEARCH_ENABLED)%"
  auth_ldap_enabled: "%env(bool:LDAP_AUTH_ENABLED)%"
  auth_database_enabled: "%env(bool:DATABASE_AUTH_ENABLED)%"
  auth_registration_enabled: "%env(bool:DATABASE_AUTH_REGISTER)%"



  elasticsearch:
    url: "%env(ELASTICSEARCH_URL)%"
    index: "%env(ELASTICSEARCH_INDEX)%"





  ldap_connection_string: "%env(LDAP_CONNECTION_STRING)%"
  ldap_bind_dn: "%env(LDAP_BIND_DN)%"
  ldap_bind_password: "%env(LDAP_BIND_PASSWORD)%"
  ldap_base_dn: "%env(LDAP_BASE_DN)%"
  ldap_user_key: "%env(LDAP_USER_KEY)%"
  ldap_auth_dn: "%env(LDAP_AUTH_DN)%"

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  App\Services\StorageManager:
    arguments:
      $storagePath: "%storage%"
  App\Services\Elasticsearch:
    arguments:
      $elasticConfig: "%elasticsearch%"
  App\Services\Search:
    arguments:
      $enableElasticsearch: "%elasticsearch_enabled%"
  App\Security\LdapClient:
    arguments:
      $connectionString: "%ldap_connection_string%"
      $bindDn: "%ldap_bind_dn%"
      $bindPassword: "%ldap_bind_password%"
      $baseDn: "%ldap_base_dn%"
      $userKey: "%ldap_user_key%"
  App\Security\UserAuthenticator:
    arguments:
      $ldapEnabled: "%auth_ldap_enabled%"
      $dbEnabled: "%auth_database_enabled%"
  # add more service definitions when explicit configuration is needed
# please note that last definitions always *replace* previous ones
